$kind: http-request
name: product
url: http://localhost:3000/products
method: POST
body:
  type: json
  content: "{\r

    \  \"name\": \"Pixel 4\",\r

    \  \"brand\": \"Google\",\r

    \  \"userId\": 1\r

    }"
order: 3457713505534672
